/* LagoNord AI · Übersetzungen der Startseite.
   Deutsch ist die Grundsprache und steht direkt im Dokument. Diese Datei bildet
   jeden deutschen Text auf Italienisch und Englisch ab — Schlüssel ist der exakte
   deutsche Wortlaut. Cristina redigiert hier, nicht im HTML.
   t = reine Texte · h = Texte mit Auszeichnung (h1/h2, Nachrichten, Notizen) */
window.LAGONORD_SPRACHEN = {
"it": { "t": {
"Leistungen":"Servizi","Beratung":"Consulenza","Beratung und Kommunikation":"Consulenza e comunicazione","Vorführung":"Dimostrazione","Ablauf":"Come lavoriamo","Warum wir":"Perché noi","Team":"Team",
"Erstgespräch":"Primo colloquio",
"KI-Assistenten für Hotellerie, Weingüter und Makler am Gardasee — auf Ihren Betrieb zugeschnitten, nicht aus dem Regal.":"Assistenti AI per hotel, cantine e agenzie immobiliari sul lago di Garda — su misura per la vostra azienda, non preconfezionati.",
"Sie führen Ihren Betrieb. Wir bauen den Assistenten, der Ihre Anfragen beantwortet, qualifiziert und vorsortiert — auf Deutsch, Italienisch und Englisch.":"Voi guidate la vostra azienda. Noi costruiamo l’assistente che risponde alle richieste, le qualifica e le smista — in tedesco, italiano e inglese.",
"Kostenloses Erstgespräch":"Primo colloquio gratuito","Assistent in Aktion sehen":"L’assistente in azione",
"Vor Ort, nicht remote":"Sul posto, non da remoto",
"Wir leben in Peschiera del Garda und besuchen jedes Haus, das wir betreuen.":"Viviamo a Peschiera del Garda e visitiamo ogni casa che seguiamo.",
"Industrieller Anspruch":"Standard industriale",
"15+ Jahre internationale IT- und Management-Beratung stecken in jedem Projekt.":"In ogni progetto ci sono 15+ anni di consulenza IT e direzionale internazionale.",
"Belegt statt erfunden":"Con riscontro, mai inventato",
"Was nicht im Wissen Ihres Hauses steht, wird nicht behauptet, sondern übergeben.":"Ciò che non sta nella conoscenza della vostra casa non viene affermato: viene passato a voi.",
"Produktlinie":"Linea di prodotto",
"Eine Grundlage, zwei Linien, fünf Rollen. Jede Rolle hat einen klaren Auftrag, einen eigenen Ton und Zugriff auf das hinterlegte Wissen Ihres Hauses — und wird einzeln eingerichtet.":"Una base, due linee, cinque ruoli. Ogni ruolo ha un incarico chiaro, un tono proprio e accesso alla conoscenza registrata della vostra casa — e si attiva singolarmente.",
"Der Zuschnitt auf Ihre Branche":"Il taglio sul vostro settore","Was Sie tatsächlich buchen":"Quello che effettivamente attivate",
"Hotels, Weingüter, Gastgeber von Erlebnissen":"Hotel, cantine e chi propone esperienze",
"Verkostungen, Zimmerfragen, Erlebnisse, Gruppen. Die Wissensvorlage kennt Öffnungszeiten, Formate, Preise, Versand und Hausregeln.":"Degustazioni, domande sulle camere, esperienze, gruppi. Il modello di conoscenza copre orari, formati, prezzi, spedizioni e regole della casa.",
"Makler und Verwalter am See":"Agenzie e gestori sul lago",
"Objektanfragen, Besichtigungstermine, Käuferqualifizierung. Dieselben Rollen, anderes Wissen — und ein Dossier statt fünf Mails.":"Richieste sugli immobili, appuntamenti di visita, qualificazione degli acquirenti. Gli stessi ruoli, altra conoscenza — e un dossier invece di cinque mail.",
"Für alles, was hereinkommt":"Per tutto ciò che arriva",
"Nimmt jede Nachricht auf, erkennt Sprache und Anliegen, legt die Antwort bereit — und zeigt, was liegen geblieben ist.":"Riceve ogni messaggio, riconosce lingua e richiesta, prepara la risposta — e mostra che cosa è rimasto fermo.",
"E-Mail · Formular":"E-mail · modulo",
"Auf Ihrer Website":"Sul vostro sito",
"Klärt rund um die Uhr, was feststeht. Aus Besuchern, die sonst weiterziehen, werden Anfragen mit Namen.":"Chiarisce in ogni momento ciò che è certo. Da visitatori che altrimenti passano oltre nascono richieste con nome.",
"Website · drei Sprachen":"Sito · tre lingue",
"Nach dem Besuch":"Dopo la visita",
"Meldet sich mit dem, was im Glas stand, und dem Versand nach Hause — mit dokumentierter Einwilligung.":"Si fa vivo con ciò che c’era nel bicchiere e la spedizione a casa — con consenso documentato.",
"Für Ihre Zeiten":"Per i vostri orari",
"Hält Ihre Verfügbarkeiten aktuell, per WhatsApp und in Ihrer Sprache. Alle anderen Rollen rechnen damit.":"Tiene aggiornate le vostre disponibilità, via WhatsApp e nella vostra lingua. Tutti gli altri ruoli ne tengono conto.",
"Für Gruppen":"Per i gruppi",
"Stellt die Rückfragen, die Sie stellen würden, und legt ein Dossier vor, in dem auch steht, was offen blieb.":"Pone le controdomande che porreste voi e presenta un dossier in cui è scritto anche ciò che è rimasto aperto.",
"Website · E-Mail":"Sito · e-mail",
"Und was noch fehlt":"E quello che ancora manca","Weitere Rollen":"Altri ruoli","in Vorbereitung":"in preparazione","In eigener Sache":"In prima persona","Beispielszenario":"Scenario di esempio","Wir arbeiten mit wenigen Häusern gleichzeitig. Erstgespräch kostenlos.":"Lavoriamo con poche case alla volta. Primo colloquio gratuito.","Unsere eigene Adresse am Gardasee — dort betreiben wir selbst, was wir hier beschreiben.":"Il nostro indirizzo sul lago di Garda — lì gestiamo noi stessi ciò che descriviamo qui.",
"Wenn bei Ihnen etwas anderes klemmt, ist das kein Sonderfall — sondern der Ausgangspunkt für die nächste Rolle.":"Se da voi il punto critico è un altro, non è un caso particolare — è il punto di partenza del ruolo successivo.",
"Nach Gespräch":"Su richiesta",
"Belegpflicht":"Obbligo di riscontro","Geltungsbereich":"Ambito","Protokoll":"Registro","Lückenliste":"Elenco delle lacune","EU-Betrieb":"Gestione UE",
"Ausserdem":"Inoltre",
"Nicht alles gehört an einen Assistenten. Diese beiden Leistungen erbringen wir selbst — mit KI beschleunigt, aber von uns verantwortet.":"Non tutto va affidato a un assistente. Questi due servizi li facciamo noi — accelerati dall’AI, ma sotto la nostra responsabilità.",
"Workshops & Schulungen":"Workshop e formazione",
"Verstehen, bevor Sie entscheiden.":"Capire, prima di decidere.",
"Von „Was ist KI?“ ohne Vorwissen bis zur Vertiefung im eigenen Betrieb — für Teams, Verbände und Unternehmen im deutschsprachigen Raum. Jeder Workshop endet mit Ihren Engstellen, nicht mit einer Verkaufsfolie.":"Da «Che cos’è l’AI?» senza prerequisiti all’approfondimento in azienda — per team, associazioni e imprese. Ogni workshop finisce con i vostri punti critici, non con una slide di vendita.",
"Termin anfragen →":"Richiedere una data →",
"Gestaltung & Kommunikation":"Design e comunicazione",
"Wer Anfragen beantwortet, muss auch gefunden werden.":"Chi risponde alle richieste deve anche farsi trovare.",
"Social Media, Texte, Bildsprache, Bewertungsantworten — in der Sprache Ihrer Gäste. Wir besuchen jedes Haus, das wir betreuen, und schreiben keine Zeile über einen Ort, an dem wir nicht waren.":"Social media, testi, immagine, risposte alle recensioni — nella lingua dei vostri ospiti. Visitiamo ogni casa che seguiamo e non scriviamo una riga su un luogo dove non siamo stati.",
"Anfragen →":"Contattarci →",
"Sehen Sie selbst":"Guardate voi stessi",
"Im Hotelzimmer über den QR-Code, im Posteingang eines Weinguts, auf der Website eines Maklers. Jedes Mal antwortet der Assistent aus hinterlegten Angaben — und übergibt, sobald ihm ein Beleg fehlt.":"In camera con il codice QR, nella casella di una cantina, sul sito di un’agenzia. Ogni volta l’assistente risponde da dati registrati — e passa a voi appena gli manca un riscontro.",
"Live-Demo anfragen":"Richiedere una demo","Broschüre als PDF":"Brochure in PDF",
"Was der Gast nicht sieht":"Quello che l’ospite non vede",
"Hausfrage erkannt":"Domanda di casa riconosciuta",
"Pool, Hunde, Frühstück — aus Ihren hinterlegten Regeln.":"Piscina, cani, colazione — dalle vostre regole registrate.",
"Sprache übernommen":"Lingua dell’ospite",
"Der Gast schreibt Deutsch, die Antwort kommt Deutsch.":"L’ospite scrive in tedesco, la risposta arriva in tedesco.",
"Grenze eingehalten":"Limite rispettato",
"Ohne belegte Angabe wird nicht geraten.":"Senza un dato con riscontro non si tira a indovinare.",
"Übergabe an die Rezeption":"Passaggio alla reception",
"Mit Zimmernummer und Anliegen, sofort.":"Con numero di camera e richiesta, subito.",
"Was im Betrieb ankommt":"Quello che arriva in azienda",
"Eckdaten herausgezogen":"Dati essenziali estratti",
"Zeitraum, Personenzahl, Wunschformat.":"Periodo, numero di persone, formato desiderato.",
"Entwurf mit Belegen":"Bozza con riscontri",
"Jede Angabe mit ihrer Herkunft.":"Ogni dato con la propria origine.",
"Nach Dringlichkeit sortiert":"In ordine di urgenza",
"Was seit Tagen liegt, steht oben.":"Ciò che è fermo da giorni sta in alto.",
"Lücke notiert":"Lacuna annotata",
"Die offene Frage landet auf der Monatsliste.":"La domanda aperta finisce nell’elenco mensile.",
"Und danach, ohne Ihr Zutun":"E poi, senza il vostro intervento",
"Anfrage bewertet":"Richiesta valutata",
"Budget, Ernsthaftigkeit und Zeitrahmen eingeschätzt.":"Budget, serietà e tempi stimati.",
"Kontakt angelegt":"Contatto registrato",
"Mit allen Angaben, an einer Stelle.":"Con tutti i dati, in un unico posto.",
"Follow-up vorbereitet":"Follow-up preparato",
"Im Kanal, den der Interessent gewählt hat.":"Nel canale scelto dall’interessato.",
"Übergabe an Sie":"Passaggio a voi",
"Nur, was wirklich trägt.":"Solo ciò che vale davvero.",
"Nimmt auf, was hereinkommt":"Riceve ciò che arriva","Objektanfragen":"Richieste immobili","Beispiel":"Esempio",
"Antwort, während der Gast noch plant":"Risposta mentre l’ospite sta ancora programmando",
"Drei Angaben belegt":"Tre dati con riscontro",
"Aus einem Besucher wird ein Gespräch":"Da un visitatore nasce una conversazione",
"Budget und Nutzung erfasst":"Budget e uso registrati",
"Ihre Farben · Ihre Hausregeln · drei Sprachen":"I vostri colori · le vostre regole · tre lingue",
"So arbeiten wir":"Come lavoriamo",
"Was von Ihnen kommt, ist Wissen — nicht Technik. Wir rechnen mit etwa drei Stunden Ihrer Zeit für die Einrichtung.":"Quello che arriva da voi è conoscenza, non tecnica. Contiamo su circa tre ore del vostro tempo per la configurazione.",
"01 · Kennenlernen":"01 · Conoscersi","Wir prüfen die Annahmen an Ihren Zahlen":"Verifichiamo le ipotesi sui vostri numeri",
"Welche Anfragen kommen herein, wie lange dauert die Antwort heute, welcher Anteil wiederholt sich. Erstgespräch kostenlos.":"Quali richieste arrivano, quanto dura oggi la risposta, quale quota si ripete. Primo colloquio gratuito.",
"02 · Einrichten":"02 · Configurare","Wir bauen mit Ihrem Wissen":"Costruiamo con la vostra conoscenza",
"Ihre Preise, Ihre Zeiten, Ihre Hausregeln — und ausdrücklich auch das, was bei Ihnen nicht geht. Sie liefern die Inhalte, die Technik übernehmen wir.":"I vostri prezzi, i vostri orari, le vostre regole — e in modo esplicito anche ciò che da voi non si può fare. Voi fornite i contenuti, la tecnica la mettiamo noi.",
"03 · Laufen lassen":"03 · Lasciar lavorare","Sie lesen mit und korrigieren":"Leggete insieme e correggete",
"Der Assistent arbeitet ab Tag eins. Was Ihnen nicht gefällt, ändern wir im Wissen — meist am selben Tag, und die Korrektur wirkt in allen Kanälen.":"L’assistente lavora dal primo giorno. Ciò che non vi piace lo cambiamo nella conoscenza — di solito in giornata, e la correzione vale su tutti i canali.",
"Warum LagoNord":"Perché LagoNord",
"Ihre Gäste und Kunden kommen aus Deutschland, Österreich und der Schweiz. Wir kommen von dort. Wir wissen, wie im deutschsprachigen Raum gefragt, verglichen und entschieden wird — und wie am Gardasee gearbeitet wird. Deshalb klingt ein Assistent von uns nicht wie eine Übersetzung, sondern wie Ihr Haus.":"I vostri ospiti e clienti arrivano da Germania, Austria e Svizzera. Noi veniamo da lì. Sappiamo come nello spazio di lingua tedesca si chiede, si confronta e si decide — e come si lavora sul lago di Garda. Per questo un nostro assistente non suona come una traduzione, ma come la vostra casa.",
"Jahre internationale IT- und Management-Beratung — digitale Transformationen in der Automobilindustrie inklusive. Wir spielen nicht mit KI, wir integrieren sie.":"Anni di consulenza IT e direzionale internazionale — trasformazioni digitali nell’automotive comprese. Non giochiamo con l’AI: la integriamo.",
"Nachvollziehbar statt magisch":"Tracciabile, non magico",
"Europäische Anbieter, Auftragsverarbeitung, Löschfristen, Zweckbindung. Auf Wunsch zeigen wir Ihnen die komplette Datenarchitektur — das ist unser Handwerk.":"Fornitori europei, responsabilità del trattamento, termini di cancellazione, vincolo di finalità. Su richiesta vi mostriamo l’intera architettura dei dati — è il nostro mestiere.",
"Wir leben am Südufer. Ihre Region ist unsere Region — wir kommen vorbei, statt Formulare zu schicken.":"Viviamo sulla sponda sud. La vostra zona è la nostra — passiamo di persona, invece di mandare moduli.",
"Wer dahinter steht":"Chi c’è dietro",
"Zwei Gründer. Ein Hund. Ein See.":"Due fondatori. Un cane. Un lago.",
"mehr erfahren →":"scopri di più →",
"Beide Gründer kommen aus der internationalen Management- und IT-Beratung und leben heute am Gardasee. Was wir für unsere Kunden bauen, betreiben wir zuerst für uns selbst.":"Entrambi i fondatori vengono dalla consulenza direzionale e IT internazionale e oggi vivono sul lago di Garda. Ciò che costruiamo per i clienti, lo usiamo prima per noi stessi.",
"Was Betriebe uns fragen":"Che cosa ci chiedono le aziende",
"Ehrlich beantwortet.":"Risposte oneste.",
"Was passiert, wenn der Assistent etwas nicht weiß?":"Che cosa succede se l’assistente non sa qualcosa?",
"Dann sagt er es — und übergibt an Sie. Die Assistenten antworten ausschließlich aus Ihrem hinterlegten Wissen; was dort nicht belegt ist, wird nicht behauptet. Fehlerfrei ist kein System dieser Art, nachvollziehbar und schnell korrigierbar schon.":"Lo dice — e passa a voi. Gli assistenti rispondono solo dalla vostra conoscenza registrata; ciò che lì non ha riscontro non viene affermato. Nessun sistema di questo tipo è privo di errori; tracciabile e correggibile in fretta sì.",
"Ist das DSGVO-konform?":"È conforme al GDPR?",
"Ja. Europäische Anbieter, Auftragsverarbeitungsvertrag, Löschfristen und Zweckbindung — jeder Beteiligte wird im Vertrag benannt. Auf Wunsch zeigen wir Ihnen die komplette Datenarchitektur; wir kommen aus der IT-Beratung, das ist unser Handwerk.":"Sì. Fornitori europei, contratto di responsabilità del trattamento, termini di cancellazione e vincolo di finalità — ogni soggetto è indicato nel contratto. Su richiesta vi mostriamo l’intera architettura dei dati; veniamo dalla consulenza IT, è il nostro mestiere.",
"Wie viel Aufwand habe ich bei der Einrichtung?":"Quanto impegno richiede la configurazione?",
"Etwa drei Stunden Ihrer Zeit: ein Kennenlern-Gespräch und Ihre Inhalte — Preise, Zeiten, Hausregeln, und ausdrücklich auch das, was bei Ihnen nicht geht. Technik, Training und Tests übernehmen wir.":"Circa tre ore del vostro tempo: un colloquio di conoscenza e i vostri contenuti — prezzi, orari, regole della casa, e in modo esplicito anche ciò che da voi non si può fare. Tecnica, addestramento e test li facciamo noi.",
"Sehe ich, was der Assistent antwortet?":"Vedo che cosa risponde l’assistente?",
"Jede Unterhaltung ist einsehbar, jeder Entwurf weist seine Belege aus. Was Ihnen nicht gefällt, ändern wir im Wissen — meist am selben Tag, und die Korrektur wirkt in allen Kanälen gleichzeitig.":"Ogni conversazione è consultabile, ogni bozza indica i propri riscontri. Ciò che non vi piace lo cambiamo nella conoscenza — di solito in giornata, e la correzione vale su tutti i canali insieme.",
"In welchen Sprachen funktioniert das?":"In quali lingue funziona?",
"Ihre Gäste erreichen die Assistenten auf Deutsch, Italienisch und Englisch. Mit Ihnen selbst spricht der Assistent in Ihrer Sprache. Weitere Gästesprachen sind möglich.":"I vostri ospiti raggiungono gli assistenti in tedesco, italiano e inglese. Con voi l’assistente parla nella vostra lingua. Altre lingue per gli ospiti sono possibili.",
"Was kostet das?":"Quanto costa?",
"Das hängt vom Umfang ab. Im kostenlosen Erstgespräch bekommen Sie eine konkrete Einschätzung — ohne Verpflichtung.":"Dipende dall’estensione. Nel primo colloquio gratuito ricevete una stima concreta — senza impegno.",
"Reden wir über Ihren Betrieb.":"Parliamo della vostra azienda.",
"Wir schauen uns an, wie viele Anfragen bei Ihnen eintreffen und wie lange sie heute liegen bleiben. Danach lässt sich sagen, was Ihnen wirklich etwas bringt.":"Guardiamo quante richieste vi arrivano e quanto restano ferme oggi. Poi si può dire che cosa vi serve davvero.",
"Gespräch vereinbaren":"Fissiamo un colloquio",
"Impressum":"Note legali","Datenschutz":"Privacy"
}, "h": {
"LagoNord AI ist Ihr <em>KI-Partner</em> am Gardasee.":"LagoNord AI è il vostro <em>partner AI</em> sul lago di Garda.",
"LagoNord <em>Assistenti</em> — digitales Personal für Ihren Betrieb.":"LagoNord <em>Assistenti</em> — personale digitale per la vostra azienda.",
"Zwei Dinge, die <em>Menschen</em> machen.":"Due cose che fanno <em>le persone</em>.",
"Drei Betriebe, drei Oberflächen — <em>dieselbe Grundlage</em>.":"Tre aziende, tre superfici — <em>la stessa base</em>.",
"Sie brauchen kein IT-Team. <em>Wir richten alles ein.</em>":"Non vi serve un reparto IT. <em>Configuriamo tutto noi.</em>",
"Wir kennen beide Seiten des Sees — <em>und beide Seiten der Alpen</em>.":"Conosciamo entrambe le sponde del lago — <em>ed entrambi i lati delle Alpi</em>.",
"Reden wir über Ihren Betrieb.":"Parliamo della vostra azienda.",
"Im Zimmer · <b>QR-Code scannen, keine App</b>":"In camera · <b>codice QR, nessuna app</b>",
"Im Betrieb · <b>alle Kanäle in einem Eingang</b>":"In azienda · <b>tutti i canali in un’unica casella</b>",
"Auf der Website · <b>rund um die Uhr erreichbar</b>":"Sul sito · <b>raggiungibile a ogni ora</b>",
"<b>Unter allen Rollen liegt dieselbe Grundlage:</b> das Wissen Ihres Hauses,\n            die Prüfung jeder Antwort gegen dieses Wissen und die Auswertung dessen, was\n            gefehlt hat. Sie wird nicht einzeln gebucht — sie ist in jeder Rolle enthalten.":"<b>Sotto tutti i ruoli sta la stessa base:</b> la conoscenza della vostra casa, il confronto di ogni risposta con quella conoscenza e la valutazione di ciò che è mancato. Non si attiva a parte — è compresa in ogni ruolo.",
"Wann ist der Pool geöffnet?":"A che ora apre la piscina?",
"Täglich von <b>8 bis 20 Uhr</b>. Handtücher bekommen Sie am Eingang.":"Tutti i giorni dalle <b>8 alle 20</b>. Gli asciugamani sono all’ingresso.",
"Sind Hunde auf der Terrasse erlaubt?":"I cani sono ammessi in terrazza?",
"Auf der Terrasse sehr gerne — im Innenraum bitten wir, darauf zu verzichten.":"In terrazza molto volentieri — all’interno chiediamo di evitare.",
"Gibt es heute Abend einen Babysitter?":"C’è una babysitter per stasera?",
"Das weiß ich nicht sicher — und ich rate nicht. Unsere Rezeption kümmert sich sofort darum.":"Non lo so con certezza — e non tiro a indovinare. La nostra reception se ne occupa subito.",
"Wir sind zu viert im September in Peschiera. Wäre am Samstag eine Verkostung möglich?":"Siamo in quattro a settembre a Peschiera. Sabato sarebbe possibile una degustazione?",
"Sehr gern — Samstag <b>11:00</b> und <b>16:00 Uhr</b> sind frei. Etwa 90 Minuten, fünf Weine, <b>25 € pro Person</b>.":"Molto volentieri — sabato alle <b>11:00</b> e alle <b>16:00</b> c’è posto. Circa 90 minuti, cinque vini, <b>25 € a persona</b>.",
"Gibt es auch einen Babysitter im Ort?":"C’è anche una babysitter in paese?",
"Dazu habe ich keine gesicherte Angabe — und ich rate nicht. Ich gebe die Frage an den Betrieb weiter.":"Su questo non ho un dato certo — e non tiro a indovinare. Passo la domanda all’azienda.",
"Wir suchen eine Wohnung am Gardasee, gerne mit Seeblick.":"Cerchiamo un appartamento sul Garda, possibilmente vista lago.",
"Gerne. <b>Zweitwohnsitz</b> oder <b>Kapitalanlage</b>? Und in welchem Budgetrahmen bewegen wir uns?":"Volentieri. <b>Seconda casa</b> o <b>investimento</b>? E in che fascia di budget ci muoviamo?",
"Zweitwohnsitz, bis etwa 450.000 €. Wichtig wäre eine Terrasse.":"Seconda casa, fino a circa 450.000 €. Importante una terrazza.",
"Notiert. In dieser Spanne lohnt der Blick nach <b>Padenghe</b> und <b>Moniga</b>. Ich lege Ihre Anfrage dem Makler vor.":"Annotato. In questa fascia vale la pena guardare <b>Padenghe</b> e <b>Moniga</b>. Presento la vostra richiesta all’agenzia."
}},
"en": { "t": {
"Leistungen":"Services","Beratung":"Consulting","Beratung und Kommunikation":"Consulting and communication","Vorführung":"Demo","Ablauf":"How it works","Warum wir":"Why us","Team":"Team",
"Erstgespräch":"Intro call",
"KI-Assistenten für Hotellerie, Weingüter und Makler am Gardasee — auf Ihren Betrieb zugeschnitten, nicht aus dem Regal.":"AI assistants for hotels, wineries and estate agents at Lake Garda — tailored to your business, not off the shelf.",
"Sie führen Ihren Betrieb. Wir bauen den Assistenten, der Ihre Anfragen beantwortet, qualifiziert und vorsortiert — auf Deutsch, Italienisch und Englisch.":"You run your business. We build the assistant that answers, qualifies and sorts your inquiries — in German, Italian and English.",
"Kostenloses Erstgespräch":"Free intro call","Assistent in Aktion sehen":"See the assistant in action",
"Vor Ort, nicht remote":"On site, not remote",
"Wir leben in Peschiera del Garda und besuchen jedes Haus, das wir betreuen.":"We live in Peschiera del Garda and visit every business we work with.",
"Industrieller Anspruch":"Industrial standards",
"15+ Jahre internationale IT- und Management-Beratung stecken in jedem Projekt.":"Every project carries 15+ years of international IT and management consulting.",
"Belegt statt erfunden":"Sourced, never invented",
"Was nicht im Wissen Ihres Hauses steht, wird nicht behauptet, sondern übergeben.":"Anything not in your house’s knowledge is never claimed — it’s handed over to you.",
"Produktlinie":"Product line",
"Eine Grundlage, zwei Linien, fünf Rollen. Jede Rolle hat einen klaren Auftrag, einen eigenen Ton und Zugriff auf das hinterlegte Wissen Ihres Hauses — und wird einzeln eingerichtet.":"One foundation, two lines, five roles. Each role has a clear mandate, its own tone and access to your house’s stored knowledge — and is set up individually.",
"Der Zuschnitt auf Ihre Branche":"Tailored to your industry","Was Sie tatsächlich buchen":"What you actually book",
"Hotels, Weingüter, Gastgeber von Erlebnissen":"Hotels, wineries, experience hosts",
"Verkostungen, Zimmerfragen, Erlebnisse, Gruppen. Die Wissensvorlage kennt Öffnungszeiten, Formate, Preise, Versand und Hausregeln.":"Tastings, room questions, experiences, groups. The knowledge template covers opening hours, formats, prices, shipping and house rules.",
"Makler und Verwalter am See":"Agents and property managers at the lake",
"Objektanfragen, Besichtigungstermine, Käuferqualifizierung. Dieselben Rollen, anderes Wissen — und ein Dossier statt fünf Mails.":"Property inquiries, viewing appointments, buyer qualification. The same roles, different knowledge — and one dossier instead of five emails.",
"Für alles, was hereinkommt":"For everything that comes in",
"Nimmt jede Nachricht auf, erkennt Sprache und Anliegen, legt die Antwort bereit — und zeigt, was liegen geblieben ist.":"Takes in every message, detects language and intent, drafts the reply — and shows what has been sitting.",
"E-Mail · Formular":"Email · form",
"Auf Ihrer Website":"On your website",
"Klärt rund um die Uhr, was feststeht. Aus Besuchern, die sonst weiterziehen, werden Anfragen mit Namen.":"Answers what’s certain, around the clock. Visitors who would move on become inquiries with a name.",
"Website · drei Sprachen":"Website · three languages",
"Nach dem Besuch":"After the visit",
"Meldet sich mit dem, was im Glas stand, und dem Versand nach Hause — mit dokumentierter Einwilligung.":"Follows up with what was in the glass and home shipping — with documented consent.",
"Für Ihre Zeiten":"For your availability",
"Hält Ihre Verfügbarkeiten aktuell, per WhatsApp und in Ihrer Sprache. Alle anderen Rollen rechnen damit.":"Keeps your availability current, via WhatsApp and in your language. Every other role relies on it.",
"Für Gruppen":"For groups",
"Stellt die Rückfragen, die Sie stellen würden, und legt ein Dossier vor, in dem auch steht, was offen blieb.":"Asks the follow-ups you would ask and delivers a dossier that also states what remained open.",
"Website · E-Mail":"Website · email",
"Und was noch fehlt":"And what’s still missing","Weitere Rollen":"Further roles","in Vorbereitung":"in preparation","In eigener Sache":"On our own account","Beispielszenario":"Example scenario","Wir arbeiten mit wenigen Häusern gleichzeitig. Erstgespräch kostenlos.":"We work with a few houses at a time. Intro call free of charge.","Unsere eigene Adresse am Gardasee — dort betreiben wir selbst, was wir hier beschreiben.":"Our own address at Lake Garda — there we run ourselves what we describe here.",
"Wenn bei Ihnen etwas anderes klemmt, ist das kein Sonderfall — sondern der Ausgangspunkt für die nächste Rolle.":"If something else is stuck at your place, that’s no edge case — it’s the starting point for the next role.",
"Nach Gespräch":"On request",
"Belegpflicht":"Evidence required","Geltungsbereich":"Scope","Protokoll":"Log","Lückenliste":"Gap list","EU-Betrieb":"EU operation",
"Ausserdem":"And also",
"Nicht alles gehört an einen Assistenten. Diese beiden Leistungen erbringen wir selbst — mit KI beschleunigt, aber von uns verantwortet.":"Not everything belongs to an assistant. These two services we deliver ourselves — AI-accelerated, but on our responsibility.",
"Workshops & Schulungen":"Workshops & training",
"Verstehen, bevor Sie entscheiden.":"Understand before you decide.",
"Von „Was ist KI?“ ohne Vorwissen bis zur Vertiefung im eigenen Betrieb — für Teams, Verbände und Unternehmen im deutschsprachigen Raum. Jeder Workshop endet mit Ihren Engstellen, nicht mit einer Verkaufsfolie.":"From “What is AI?” with no prerequisites to deep dives in your own business — for teams, associations and companies. Every workshop ends with your bottlenecks, not a sales slide.",
"Termin anfragen →":"Request a date →",
"Gestaltung & Kommunikation":"Design & communication",
"Wer Anfragen beantwortet, muss auch gefunden werden.":"Whoever answers inquiries must also be found.",
"Social Media, Texte, Bildsprache, Bewertungsantworten — in der Sprache Ihrer Gäste. Wir besuchen jedes Haus, das wir betreuen, und schreiben keine Zeile über einen Ort, an dem wir nicht waren.":"Social media, copy, imagery, review replies — in your guests’ language. We visit every business we work with and never write a line about a place we haven’t been.",
"Anfragen →":"Get in touch →",
"Sehen Sie selbst":"See for yourself",
"Im Hotelzimmer über den QR-Code, im Posteingang eines Weinguts, auf der Website eines Maklers. Jedes Mal antwortet der Assistent aus hinterlegten Angaben — und übergibt, sobald ihm ein Beleg fehlt.":"In the hotel room via QR code, in a winery’s inbox, on an agent’s website. Each time the assistant answers from stored facts — and hands over the moment evidence is missing.",
"Live-Demo anfragen":"Request a live demo","Broschüre als PDF":"Brochure (PDF, German)",
"Was der Gast nicht sieht":"What the guest doesn’t see",
"Hausfrage erkannt":"House question recognised",
"Pool, Hunde, Frühstück — aus Ihren hinterlegten Regeln.":"Pool, dogs, breakfast — from your stored rules.",
"Sprache übernommen":"Language matched",
"Der Gast schreibt Deutsch, die Antwort kommt Deutsch.":"The guest writes German, the reply comes back in German.",
"Grenze eingehalten":"Limits respected",
"Ohne belegte Angabe wird nicht geraten.":"No guessing without a sourced fact.",
"Übergabe an die Rezeption":"Handover to reception",
"Mit Zimmernummer und Anliegen, sofort.":"With room number and request, instantly.",
"Was im Betrieb ankommt":"What arrives at the business",
"Eckdaten herausgezogen":"Key facts extracted",
"Zeitraum, Personenzahl, Wunschformat.":"Dates, party size, preferred format.",
"Entwurf mit Belegen":"Draft with sources",
"Jede Angabe mit ihrer Herkunft.":"Every fact with its origin.",
"Nach Dringlichkeit sortiert":"Sorted by urgency",
"Was seit Tagen liegt, steht oben.":"What has been sitting for days goes on top.",
"Lücke notiert":"Gap recorded",
"Die offene Frage landet auf der Monatsliste.":"The open question lands on the monthly list.",
"Und danach, ohne Ihr Zutun":"And afterwards, without your effort",
"Anfrage bewertet":"Inquiry rated",
"Budget, Ernsthaftigkeit und Zeitrahmen eingeschätzt.":"Budget, seriousness and timeframe assessed.",
"Kontakt angelegt":"Contact created",
"Mit allen Angaben, an einer Stelle.":"All details, in one place.",
"Follow-up vorbereitet":"Follow-up prepared",
"Im Kanal, den der Interessent gewählt hat.":"In the channel the prospect chose.",
"Übergabe an Sie":"Handover to you",
"Nur, was wirklich trägt.":"Only what truly qualifies.",
"Nimmt auf, was hereinkommt":"Takes in whatever comes","Objektanfragen":"Property inquiries","Beispiel":"Example",
"Antwort, während der Gast noch plant":"An answer while the guest is still planning",
"Drei Angaben belegt":"Three facts sourced",
"Aus einem Besucher wird ein Gespräch":"A visitor becomes a conversation",
"Budget und Nutzung erfasst":"Budget and use captured",
"Ihre Farben · Ihre Hausregeln · drei Sprachen":"Your colours · your house rules · three languages",
"So arbeiten wir":"How we work",
"Was von Ihnen kommt, ist Wissen — nicht Technik. Wir rechnen mit etwa drei Stunden Ihrer Zeit für die Einrichtung.":"What we need from you is knowledge — not technology. Expect about three hours of your time for setup.",
"01 · Kennenlernen":"01 · Get to know","Wir prüfen die Annahmen an Ihren Zahlen":"We test the assumptions against your numbers",
"Welche Anfragen kommen herein, wie lange dauert die Antwort heute, welcher Anteil wiederholt sich. Erstgespräch kostenlos.":"Which inquiries come in, how long replies take today, what share repeats. Intro call free of charge.",
"02 · Einrichten":"02 · Set up","Wir bauen mit Ihrem Wissen":"We build with your knowledge",
"Ihre Preise, Ihre Zeiten, Ihre Hausregeln — und ausdrücklich auch das, was bei Ihnen nicht geht. Sie liefern die Inhalte, die Technik übernehmen wir.":"Your prices, your hours, your house rules — and explicitly what’s not possible at your place. You provide the content, we handle the technology.",
"03 · Laufen lassen":"03 · Let it run","Sie lesen mit und korrigieren":"You read along and correct",
"Der Assistent arbeitet ab Tag eins. Was Ihnen nicht gefällt, ändern wir im Wissen — meist am selben Tag, und die Korrektur wirkt in allen Kanälen.":"The assistant works from day one. Anything you dislike we change in the knowledge — usually same day, and the fix applies across all channels.",
"Warum LagoNord":"Why LagoNord",
"Ihre Gäste und Kunden kommen aus Deutschland, Österreich und der Schweiz. Wir kommen von dort. Wir wissen, wie im deutschsprachigen Raum gefragt, verglichen und entschieden wird — und wie am Gardasee gearbeitet wird. Deshalb klingt ein Assistent von uns nicht wie eine Übersetzung, sondern wie Ihr Haus.":"Your guests and clients come from Germany, Austria and Switzerland. So do we. We know how the German-speaking world asks, compares and decides — and how Lake Garda works. That’s why our assistants don’t sound like a translation, but like your house.",
"Jahre internationale IT- und Management-Beratung — digitale Transformationen in der Automobilindustrie inklusive. Wir spielen nicht mit KI, wir integrieren sie.":"Years of international IT and management consulting — including digital transformations in the automotive industry. We don’t play with AI, we integrate it.",
"Nachvollziehbar statt magisch":"Traceable, not magical",
"Europäische Anbieter, Auftragsverarbeitung, Löschfristen, Zweckbindung. Auf Wunsch zeigen wir Ihnen die komplette Datenarchitektur — das ist unser Handwerk.":"European providers, data processing agreements, deletion terms, purpose limitation. On request we’ll walk you through the entire data architecture — that’s our craft.",
"Wir leben am Südufer. Ihre Region ist unsere Region — wir kommen vorbei, statt Formulare zu schicken.":"We live on the southern shore. Your region is ours — we come by instead of sending forms.",
"Wer dahinter steht":"Who’s behind it",
"Zwei Gründer. Ein Hund. Ein See.":"Two founders. One dog. One lake.",
"mehr erfahren →":"learn more →",
"Beide Gründer kommen aus der internationalen Management- und IT-Beratung und leben heute am Gardasee. Was wir für unsere Kunden bauen, betreiben wir zuerst für uns selbst.":"Both founders come from international management and IT consulting and live at Lake Garda today. What we build for clients, we run for ourselves first.",
"Was Betriebe uns fragen":"What businesses ask us",
"Ehrlich beantwortet.":"Answered honestly.",
"Was passiert, wenn der Assistent etwas nicht weiß?":"What happens when the assistant doesn’t know something?",
"Dann sagt er es — und übergibt an Sie. Die Assistenten antworten ausschließlich aus Ihrem hinterlegten Wissen; was dort nicht belegt ist, wird nicht behauptet. Fehlerfrei ist kein System dieser Art, nachvollziehbar und schnell korrigierbar schon.":"It says so — and hands over to you. The assistants answer only from your stored knowledge; whatever isn’t sourced there is never claimed. No system of this kind is error-free; traceable and quickly correctable, yes.",
"Ist das DSGVO-konform?":"Is this GDPR-compliant?",
"Ja. Europäische Anbieter, Auftragsverarbeitungsvertrag, Löschfristen und Zweckbindung — jeder Beteiligte wird im Vertrag benannt. Auf Wunsch zeigen wir Ihnen die komplette Datenarchitektur; wir kommen aus der IT-Beratung, das ist unser Handwerk.":"Yes. European providers, a data processing agreement, deletion terms and purpose limitation — every party is named in the contract. On request we’ll show you the full data architecture; we come from IT consulting, it’s our craft.",
"Wie viel Aufwand habe ich bei der Einrichtung?":"How much effort is setup for me?",
"Etwa drei Stunden Ihrer Zeit: ein Kennenlern-Gespräch und Ihre Inhalte — Preise, Zeiten, Hausregeln, und ausdrücklich auch das, was bei Ihnen nicht geht. Technik, Training und Tests übernehmen wir.":"About three hours of your time: an intro conversation and your content — prices, hours, house rules, and explicitly what’s not possible at your place. Technology, training and testing are on us.",
"Sehe ich, was der Assistent antwortet?":"Do I see what the assistant replies?",
"Jede Unterhaltung ist einsehbar, jeder Entwurf weist seine Belege aus. Was Ihnen nicht gefällt, ändern wir im Wissen — meist am selben Tag, und die Korrektur wirkt in allen Kanälen gleichzeitig.":"Every conversation is reviewable, every draft states its sources. Anything you dislike we change in the knowledge — usually same day, and the fix applies across all channels at once.",
"In welchen Sprachen funktioniert das?":"Which languages does it work in?",
"Ihre Gäste erreichen die Assistenten auf Deutsch, Italienisch und Englisch. Mit Ihnen selbst spricht der Assistent in Ihrer Sprache. Weitere Gästesprachen sind möglich.":"Your guests reach the assistants in German, Italian and English. With you, the assistant speaks your language. Further guest languages are possible.",
"Was kostet das?":"What does it cost?",
"Das hängt vom Umfang ab. Im kostenlosen Erstgespräch bekommen Sie eine konkrete Einschätzung — ohne Verpflichtung.":"That depends on scope. In the free intro call you’ll get a concrete estimate — no obligation.",
"Reden wir über Ihren Betrieb.":"Let’s talk about your business.",
"Wir schauen uns an, wie viele Anfragen bei Ihnen eintreffen und wie lange sie heute liegen bleiben. Danach lässt sich sagen, was Ihnen wirklich etwas bringt.":"We’ll look at how many inquiries you receive and how long they sit today. Then we can tell what will actually help you.",
"Gespräch vereinbaren":"Book a call",
"Impressum":"Imprint","Datenschutz":"Privacy"
}, "hx": {} },
};
/* Englische Auszeichnungstexte */
window.LAGONORD_SPRACHEN.en.h = {
"LagoNord AI ist Ihr <em>KI-Partner</em> am Gardasee.":"LagoNord AI is your <em>AI partner</em> at Lake Garda.",
"LagoNord <em>Assistenti</em> — digitales Personal für Ihren Betrieb.":"LagoNord <em>Assistenti</em> — digital staff for your business.",
"Zwei Dinge, die <em>Menschen</em> machen.":"Two things <em>humans</em> do.",
"Drei Betriebe, drei Oberflächen — <em>dieselbe Grundlage</em>.":"Three businesses, three surfaces — <em>the same foundation</em>.",
"Sie brauchen kein IT-Team. <em>Wir richten alles ein.</em>":"You don’t need an IT team. <em>We set everything up.</em>",
"Wir kennen beide Seiten des Sees — <em>und beide Seiten der Alpen</em>.":"We know both sides of the lake — <em>and both sides of the Alps</em>.",
"Reden wir über Ihren Betrieb.":"Let’s talk about your business.",
"Im Zimmer · <b>QR-Code scannen, keine App</b>":"In the room · <b>scan the QR code, no app</b>",
"Im Betrieb · <b>alle Kanäle in einem Eingang</b>":"At the business · <b>every channel in one inbox</b>",
"Auf der Website · <b>rund um die Uhr erreichbar</b>":"On the website · <b>available around the clock</b>",
"<b>Unter allen Rollen liegt dieselbe Grundlage:</b> das Wissen Ihres Hauses,\n            die Prüfung jeder Antwort gegen dieses Wissen und die Auswertung dessen, was\n            gefehlt hat. Sie wird nicht einzeln gebucht — sie ist in jeder Rolle enthalten.":"<b>Beneath every role lies the same foundation:</b> your house’s knowledge, the check of every answer against that knowledge, and the review of what was missing. It isn’t booked separately — it’s included in every role.",
"Wann ist der Pool geöffnet?":"When is the pool open?",
"Täglich von <b>8 bis 20 Uhr</b>. Handtücher bekommen Sie am Eingang.":"Daily from <b>8 am to 8 pm</b>. Towels are at the entrance.",
"Sind Hunde auf der Terrasse erlaubt?":"Are dogs allowed on the terrace?",
"Auf der Terrasse sehr gerne — im Innenraum bitten wir, darauf zu verzichten.":"On the terrace, gladly — indoors we kindly ask you to refrain.",
"Gibt es heute Abend einen Babysitter?":"Is there a babysitter tonight?",
"Das weiß ich nicht sicher — und ich rate nicht. Unsere Rezeption kümmert sich sofort darum.":"I don’t know for certain — and I don’t guess. Our reception will take care of it right away.",
"Wir sind zu viert im September in Peschiera. Wäre am Samstag eine Verkostung möglich?":"We’re four people in Peschiera in September. Would a tasting be possible on Saturday?",
"Sehr gern — Samstag <b>11:00</b> und <b>16:00 Uhr</b> sind frei. Etwa 90 Minuten, fünf Weine, <b>25 € pro Person</b>.":"Gladly — Saturday <b>11 am</b> and <b>4 pm</b> are free. About 90 minutes, five wines, <b>€25 per person</b>.",
"Gibt es auch einen Babysitter im Ort?":"Is there a babysitter in town as well?",
"Dazu habe ich keine gesicherte Angabe — und ich rate nicht. Ich gebe die Frage an den Betrieb weiter.":"I have no sourced fact on that — and I don’t guess. I’ll pass the question to the business.",
"Wir suchen eine Wohnung am Gardasee, gerne mit Seeblick.":"We’re looking for an apartment at Lake Garda, ideally with a lake view.",
"Gerne. <b>Zweitwohnsitz</b> oder <b>Kapitalanlage</b>? Und in welchem Budgetrahmen bewegen wir uns?":"Gladly. <b>Second home</b> or <b>investment</b>? And what budget range are we in?",
"Zweitwohnsitz, bis etwa 450.000 €. Wichtig wäre eine Terrasse.":"Second home, up to about €450,000. A terrace would matter.",
"Notiert. In dieser Spanne lohnt der Blick nach <b>Padenghe</b> und <b>Moniga</b>. Ich lege Ihre Anfrage dem Makler vor.":"Noted. In that range, <b>Padenghe</b> and <b>Moniga</b> are worth a look. I’ll put your inquiry to the agent."
};
/* Team-Biografien je Sprache — Deutsch bleibt im Dokument. */
window.LAGONORD_BIOS = {
"it": {
 c: '<p>«Da ingegnere gestionale ed ex consulente strategica presso la più grande società di consulenza IT al mondo, so come si guidano i grandi progetti. Oggi uso questa precisione per portare i marchi al vertice, visivamente — niente soluzioni standard, solo immagini e strategie su misura che funzionano.»</p><p>Questa passione la vive anche nel privato: come autrice scrive libri per bambini e ricettari per genitori che lavorano.</p>',
 t: '<p>«Vengo dal mondo dei fatti concreti e dei processi complessi. Come ingegnere gestionale e Associated Partner di una nota società di consulenza direzionale e IT ho guidato trasformazioni digitali nell’industria automobilistica.»</p><p>«Non gioco con l’AI: la integro. Costruisco architetture scalabili e sicure per la vostra azienda, con gli stessi standard di qualità dell’industria.»</p>',
 l: '<p>«Sono l’esperta di algoritmi analogici — la prova vivente che l’Intelligenza Naturale conta almeno quanto quella artificiale.»</p><p>Testa personalmente ogni consiglio: dalla spiaggia di Manerba alla gelateria di Lazise.</p>'
},
"en": {
 c: '<p>“As an industrial engineer and former strategy consultant at the world’s largest IT consultancy, I know how to run large projects. Today I use that precision to take brands to the top visually — no off-the-shelf solutions, only tailored imagery and strategies that work.”</p><p>She lives that passion privately too: as an author she writes children’s books and cookbooks for working parents.</p>',
 t: '<p>“I come from the world of hard facts and complex processes. As an industrial engineer and Associated Partner of a renowned management and IT consultancy, I was responsible for digital transformations in the automotive industry.”</p><p>“I don’t play with AI, I integrate it. I build scalable, secure architectures for your business that meet the same quality standards as industry.”</p>',
 l: '<p>“I’m the expert for analogue algorithms — living proof that Natural Intelligence matters at least as much as the artificial kind.”</p><p>She personally tests every recommendation, from the beach in Manerba to the gelateria in Lazise.</p>'
}
};
